### ISSUE TITLE
use with DITA-OT?

### ISSUE THREAD

**Issue by c-alpha** [xmlark/xslthl#10]
Hi, I'm attempting to extend a DITA-OT plugin to use `xslthl`. I have downloaded the release package from SF (dated 2014), but the transformation fails with `Cannot find a 3-argument function named Q{http://net.sf.xslthl/ConnectorSaxon6}highlight()`, and like messages for the other two connectors.

Looking through the DITA-OT [Implementing Saxon extension functions](https://www.dita-ot.org/3.5/topics/implement-saxon-extension-functions.html) manual, it seems `xslthl` might need to be updated to work with Saxon 9? Just my 2 cents anyway...

Looking forward to your thoughts!

**Comment by c-alpha** [comment]
Just noticed PR #5. To my understanding, that PR would address my problem, too?

**Comment by c-alpha** [comment]
Ping?

**Comment by c-alpha** [comment]
ping?

**Comment by raducoravu** [comment]
We have a commercial DITA OT plugin which does syntax highlight using XSLTHL.
The DITA OT does not contain the Saxon 6 libraries, it contains the Saxon HE 10 libraries.
So your stylesheet would need to declare a namespace like this:

      xmlns:ConnectorSaxonEE="java:net.sf.xslthl.ConnectorSaxonEE"

and use it something like:

         <xsl:apply-templates 
      select="ConnectorSaxonEE:highlight($type, $textValue, $config-base-uri)"/>

**Comment by c-alpha** [comment]
@raducoravu, thanks for your response, and sharing your insight. Due to the changes to the extensions mechanism introduced with Saxon 9.2 (see the link in my initial message), referencing the current Saxon HE 10 namespace is not enough, and changes in the Java code are needed.

I have thus done two things:
1. build the 2.1.4-snapshot jar from this repo;
2. build a new wrapper around that jar file, which implements the new Saxon extension mechanism (as described in [Implementing Saxon extension functions](https://www.dita-ot.org/3.5/topics/implement-saxon-extension-functions.html)) and calls out to the highlight function in the 2.1.4-snapshot jar file.

This works for me.

**Many thanks again!**

**Comment by raducoravu** [comment]
@c-alpha right, forgot about this. I had kept the ConnectorSaxonEE Java class in this project compatible with Saxon HE 10.6 but forgot that we also have a Java extension function which calls it from our commercial DITA OT SH plugin.
